sudo: required
services:
  -docker

before_install:
  - docker build -t icarusv2/doc-react -f Dockerfile.dev .

script:
  - docker run -e CI=true icarusv2/doc-react npm run test 


deploy:
  edge:
    source: 'native-api/dpl'
    branch: 'ebs_session_token'
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "doc-react"
  env: "Docreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-818126042965"
  bucket_path: "doc-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  session_token: "$AWS_SESSION_TOKEN"